name: CustomJoinMessages
version: '1.0-SNAPSHOT'
main: fr.ixsou.customJoinmessages.CustomJoinMessages
api-version: '1.21'
authors: [ Ixsou_mod ]
commands:
  customjoinmessages:
    description: CustomJoinMessages command
    usage: /customjoinmessages
    permission: customjoinmessages.admin
    aliases: [ cjm ]
  joinmessages:
    description: CustomJoinMessages command
    usage: /joinmessage
    permission: customjoinmessages.use
    aliases: [ jm ]
permissions:
  customjoinmessages.use:
    default: true